### ISSUE TITLE
AppleRules.conf 有一行好像有错

### ISSUE THREAD

**Issue by ma20236544** [dunlanl/FuGfConfig#2]
我把你的Apple分流用进了我的Clash规则里，在# Apple List 下面有一行DOMAIN-SUFFIX.com好像是写错了，导致配置文件无法加载（我知道可能这个规则本身不是用于Clash的，所以我也不确定是不是写错了），但是分流用起来非常的不错！

文件在ConfigFile/Loon/LoonRemoteRule/Apple/AppleRules.conf

**Comment by dunlanl** [comment]
> 我把你的Apple分流用进了我的Clash规则里，在# Apple List 下面有一行DOMAIN-SUFFIX.com好像是写错了，导致配置文件无法加载（我知道可能这个规则本身不是用于Clash的，所以我也不确定是不是写错了），但是分流用起来非常的不错！
> 
> 
> 
> 文件在ConfigFile/Loon/LoonRemoteRule/Apple/AppleRules.conf

感谢,非常感谢,会在稍晚修复

clash文件夹里面的您可以看着用,虽然只有去广告更新的比较频繁

**Comment by dunlanl** [comment]
已修复
