### ISSUE TITLE
Google Analytics被阻断

### ISSUE THREAD

**Issue by moyuwuhen601** [dunlanl/FuGfConfig#4]
https://raw.githubusercontent.com/dunlanl/FuGfConfig/main/ConfigFile/Loon/LoonRemoteRule/Advertising/AdRules.conf
loon使用如上规则会使得谷歌分析(Google Analytics)官网被阻断，希望可以修改一下。

**Comment by moyuwuhen601** [comment]
> https://raw.githubusercontent.com/dunlanl/FuGfConfig/main/ConfigFile/Loon/LoonRemoteRule/Advertising/AdRules.conf
> loon使用如上规则会使得谷歌分析(Google Analytics)官网被阻断，希望可以修改一下。
谷歌分析官网：https://analytics.google.com/analytics/web/

**Comment by dunlanl** [comment]
感谢反馈，已修复
