### ISSUE TITLE
README 里有很多文件路径不对

### ISSUE THREAD

**Issue by h6fYe34KFSiH** [dunlanl/FuGfConfig#6]
例如
https://raw.githubusercontent.com/dunlanl/FuGfConfig/main/ConfigFile/Loon/GFWRules.conf
应该是
https://raw.githubusercontent.com/dunlanl/FuGfConfig/main/ConfigFile/Loon/LoonRemoteRule/GFWRules.conf

**Comment by dunlanl** [comment]
感谢指正 下午修复

**Comment by dunlanl** [comment]
已修复
